name: power_diyala
description: "A new app to make our job easy"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.24.10+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  table_calendar: ^3.1.2
  sqflite_sqlcipher: ^3.1.0+1
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.0
  simple_icons: ^10.1.3
  flutter_colorpicker: ^1.1.0
  fl_chart: ^0.69.0
  excel: ^4.0.6
  device_info_plus: ^11.0.0


  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  assets:
  - assets/the_data.db
  - assets/
  -  .env
  - assets/excel/



