name: power_diyala
description: "A new app to make our job easy"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.9.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  table_calendar: ^3.1.2





  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true


  assets:
  - assets/database10.db
  - assets/



