name: power_diyala
description: "A full-power aio team helper"
publish_to: 'none'
version: 0.25.02+5

environment:
  sdk: ^3.5.3

# ---------------------- PACKAGES ---------------------#
dependencies:
  flutter:
    sdk: flutter
    # Icons
  cupertino_icons: ^1.0.8
  simple_icons: ^10.1.3

    # Utility
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.20.1
  logger: ^2.4.0
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  fluttertoast: ^8.2.8
  url_launcher: ^6.3.0
  table_calendar: ^3.2.0
  fl_chart: ^0.70.2
  device_info_plus: ^11.2.1
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  flutter_speed_dial: ^7.0.0
  app_settings: ^5.1.1
  marquee: ^2.3.0
  lottie: ^3.1.3
  flutter_native_splash: ^2.4.2
  connectivity_plus: ^6.1.2
  flutter_email_sender: ^6.0.3
  image_picker: ^1.1.2
  maps_launcher: ^3.0.0+1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^4.0.0

    # Storage
  shared_preferences: ^2.3.5
  sqflite_sqlcipher: ^3.1.0+1

    # State Management
  provider: ^6.1.2

    # Pickers
  file_picker: ^8.1.2
  flutter_colorpicker: ^1.1.0
  flutter_datetime_picker_plus: ^2.2.0


   # Firebase & Utility
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_remote_config: ^5.4.1
  firebase_analytics: ^11.4.3
  supabase_flutter: ^2.8.3


# ---------------------- END OF PACKAGES ---------------------#
dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

# ---------------------- ASSETS ---------------------#

  assets:
  - assets/the_data.db
  - assets/
  -  .env
  - assets/powerdiyala.json



